spring.datasource.url=jdbc:h2:file:./db/db_cgb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sio
spring.datasource.password=slam
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
# spring.datasource.hikari.auto-commit=true
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create

spring.h2.console.settings.web-allow-others=true
spring.h2.console.enabled=true
spring.datasource.initialize=true 
spring.error.whitelabel.enabled=true
spring.h2.console.path=/console
spring.datasource.continue-on-error=true
#spring.jpa.hibernate.ddl-auto=create
#spring.hibernate.hbm2ddl.auto=update
spring.hibernate.show_sql=true

# Configuration avec Mailtrap.io
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=587
#spring.mail.username=3b4b5a9574fe67
#spring.mail.password=7d041dbc069d08

# Configuration avec Papercut local
spring.mail.host=127.0.0.1
spring.mail.port=25
spring.mail.username=quoi
spring.mail.password=coubeh
